pipeline {
    agent any
    
    tools {
        maven 'Maven3'
    }

    environment {
        NEXUS_CRED_ID = 'nexus-auth'
        SONAR_PROJECT_KEY = 'java-webapp'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('SonarQube Analysis') {
            steps {
                script {
                    def scannerHome = tool 'SonarScanner' // Ensure you have a 'SonarScanner' defined in Global Tool Configuration
                    withSonarQubeEnv('SonarQube') {
                        sh "mvn -f smartops-backend/pom.xml sonar:sonar \
                            -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
                            -Dsonar.projectName=${SONAR_PROJECT_KEY}"
                    }
                }
            }
        }

        stage("Quality Gate") {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
        
        stage('Build & Deploy to Nexus') {
            steps {
                configFileProvider([configFile(fileId: 'caprivax-maven-settings', variable: 'MAVEN_SETTINGS')]) {
                    withCredentials([usernamePassword(credentialsId: "${NEXUS_CRED_ID}", passwordVariable: 'NEXUS_PWD', usernameVariable: 'NEXUS_USR')]) {
                        sh "mvn -s $MAVEN_SETTINGS -f smartops-backend/pom.xml clean deploy -DskipTests"
                    }
                }
            }
        }
    }
}
